-- DB ADMINISTRATOR USER
CREATE USER "C##STAGEUPDBA" IDENTIFIED BY "stageupdba"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##STAGEUPDBA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##STAGEUPDBA" ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT ALTER ANY INDEX TO "C##STAGEUPDBA" ;
GRANT DROP ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE TRIGGER TO "C##STAGEUPDBA" ;
GRANT ALTER ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY INDEX TO "C##STAGEUPDBA" ;
GRANT CREATE OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE VIEW TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TABLE TO "C##STAGEUPDBA" ;
GRANT SELECT ANY TABLE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE TABLESPACE TO "C##STAGEUPDBA" ;
GRANT DROP ANY TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY SYNONYM TO "C##STAGEUPDBA" ;
GRANT DROP ANY SYNONYM TO "C##STAGEUPDBA" ;
GRANT EXECUTE ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE SYNONYM TO "C##STAGEUPDBA" ;
GRANT CREATE SEQUENCE TO "C##STAGEUPDBA" ;
GRANT DROP ANY INDEX TO "C##STAGEUPDBA" ;
GRANT EXECUTE ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT UPDATE ANY TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY VIEW TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT CREATE ANY VIEW TO "C##STAGEUPDBA" ;
GRANT READ ANY TABLE TO "C##STAGEUPDBA" ;
GRANT INSERT ANY TABLE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TYPE TO "C##STAGEUPDBA" ;
GRANT DROP ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TABLE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE PROCEDURE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY OPERATOR TO "C##STAGEUPDBA" ;

-- -- LOGISTIC TEAM USER
-- CREATE USER "C##LOGISTICTEAM_USER" IDENTIFIED BY "logisticteam"
-- DEFAULT TABLESPACE "USERS"
-- TEMPORARY TABLESPACE "TEMP";

-- -- QUOTAS
-- ALTER USER "C##LOGISTICTEAM_USER" QUOTA UNLIMITED ON "USERS";

-- -- ROLES
-- GRANT "CONNECT" TO "C##LOGISTICTEAM_USER" ;

-- -- OBJECT PRIVILEGES
-- -- Grant SELECT, INSERT, UPDATE, DELETE on specific tables.
-- -- A logistic team would likely view orders, update their status,
-- -- and perhaps view product batches.
-- GRANT SELECT, UPDATE ON "C##STAGEUPDBA".BatchOrder TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".ProductBatch TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".Product TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".Customer TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".LogisticTeam TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".ChiefOfficier TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".TeamMember TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".Department TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".DistributionCenter TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##STAGEUPDBA".Complaint TO "C##LOGISTICTEAM_USER" ;


-- -- Grant EXECUTE on necessary object types for DEREF and object creation/manipulation
-- GRANT EXECUTE ON "C##STAGEUPDBA".Location TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".ContactInfo TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".PhoneList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".Product_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".ProdBatch_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".Customer_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".Department_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".DepartmentList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".TeamMember_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".ChiefOfficier_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".MemberList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".LogisticTeam_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".DistCenter_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".ProductList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".BatchOrder_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".BatchList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##STAGEUPDBA".PreferencesList TO "C##LOGISTICTEAM_USER" ;

COMMIT;