-- DB ADMINISTRATOR USER
CREATE USER "C##STAGEUPDBA" IDENTIFIED BY "stageupdba"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##STAGEUPDBA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##STAGEUPDBA" ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT ALTER ANY INDEX TO "C##STAGEUPDBA" ;
GRANT DROP ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE TRIGGER TO "C##STAGEUPDBA" ;
GRANT ALTER ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY INDEX TO "C##STAGEUPDBA" ;
GRANT CREATE OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE VIEW TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TABLE TO "C##STAGEUPDBA" ;
GRANT SELECT ANY TABLE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY SEQUENCE TO "C##STAGEUPDBA" ;
GRANT CREATE TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT CREATE TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE TABLESPACE TO "C##STAGEUPDBA" ;
GRANT DROP ANY TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY SYNONYM TO "C##STAGEUPDBA" ;
GRANT DROP ANY SYNONYM TO "C##STAGEUPDBA" ;
GRANT EXECUTE ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE SYNONYM TO "C##STAGEUPDBA" ;
GRANT CREATE SEQUENCE TO "C##STAGEUPDBA" ;
GRANT DROP ANY INDEX TO "C##STAGEUPDBA" ;
GRANT EXECUTE ANY OPERATOR TO "C##STAGEUPDBA" ;
GRANT UPDATE ANY TABLE TO "C##STAGEUPDBA" ;
GRANT DROP ANY VIEW TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT CREATE ANY VIEW TO "C##STAGEUPDBA" ;
GRANT READ ANY TABLE TO "C##STAGEUPDBA" ;
GRANT INSERT ANY TABLE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY TYPE TO "C##STAGEUPDBA" ;
GRANT DROP ANY PROCEDURE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TRIGGER TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TABLE TO "C##STAGEUPDBA" ;
GRANT CREATE ANY TYPE TO "C##STAGEUPDBA" ;
GRANT CREATE PROCEDURE TO "C##STAGEUPDBA" ;
GRANT ALTER ANY OPERATOR TO "C##STAGEUPDBA" ;

COMMIT;